#!/bin/bash
# This only works on CSE because I could not figure out how to do this for every OS


# Initialise virtualenv
venv source/bin/activate
xterm -e python3 app.py

xterm -e cd frontend && npm start
